language: python
services:
  - postgresql
  - redis-server
python:
  - "3.5.1"
before_script:
#- export DATABASE_URL=postgres://postgres@localhost/{{ cookiecutter.app_name }}
- export DJANGO_SECRET=`openssl rand -base64 32`
#- psql -c 'CREATE DATABASE "{{ cookiecutter.app_name }}";' -U postgres
install:
  - "pip install -r requirements.txt"
script:
  - ./antlia/manage.py test antlia
after_success:
  - coveralls

deploy:
  provider: heroku
  app:
    master: antlia-geislor
  on:
    repo: geislor/antlia
  run:
    - "./antlia/manage.py migrate"

notifications:
  email: false

# This reportedly works around an issue downloading packages from pypi on
# travis. Consider removing this after the underlying issue is fixed.
# https://github.com/travis-ci/travis-ci/issues/2389
sudo: false

matrix:
  fast_finish: true