language: python
services:
- postgresql
- redis-server
python:
- 3.5.1
before_script:
- export DJANGO_SECRET=`openssl rand -base64 32`
install:
- pip install -r requirements.txt
script:
- "./manage.py test"
after_success:
- coveralls
deploy:
  provider: heroku
  api_key:
    secure: Kj+hlADjMxm2O3uLdavzeMCrAiIEGKGPbgu3QeZmGDJAhdAx5WW9IOOeka2ONG8RvOgdJ+viHRy9tHNFgu4A5dh1roMQirrGqGTTBOb2nuDs8KErPgdwHqKUfgrd/BrLdvZMv0jLmWgRcKcIC9HnZlImkdW+MbtQE2HBvJuc3tYENf56HQ/2q01YX/bEYGgOyZmELJCjKcSu7qtKKN04tS2J6RXbJq8/ksJJc4I7Q81+iTRU16AT7dt0WR3lMuLqi4nlCDSl2MXlLoYd2Cjhx1eHW7Eku71Kxn6/aCh5s3mHpv7C4YB0hA8IuPYy0TcBowh0zZr9D8IeyshMRawOF+0IiwpLR0LGS5zPYiRoSEh3rUa11dxVItqMeD6zykIPzXidZPRIzWJczP06pdQGOz0FB7Et2EjE+nzegjmCuK8+7KdXcDwJ0NYtDDaMDU2AGA02Ptnsh3yplgNBxvNgN1NxM+zjHLagBuK9BDe+iFFYfE22Tuh5rL2R0y0ap8KN1jB3ahnwPERwIyoDX8L57g/XwnCgGKe2qs7hMeHrPsGD8NQkuk4cEAiB94/GPvKdQI6cBCFwe6gMiGTuwSrlVR1bxgHL2RW1oTn/pKHEe920vt5J2xA6YwDkHtV49aoX1N5FvgVQfSjquo4F+TuUj/+7hVJ7Yan5DC8Mrv4nBns=
  app: antlia-geislor
  on:
    repo: geislor/antlia
notifications:
  email: false
sudo: false
matrix:
  fast_finish: true
